- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  
     - name: Check Azure VM Status
       stat:
         path: host_ip.txt
       register: stat_result
       set_fact: stat_result

     - name: Execute the azure VM creation script
       script: create_az_vm.sh
       when: stat_result.stat.exists == False

     - name: Execute the fetch IP script
       script: getazvmip.sh
       register: task_result
       until: task_result.rc == 0
       retries: 3
       delay: 
       when: stat_result.stat.exists == False

     - name: Retrieve Host IP from file
       command: cat "host_ip.txt"
       register: hostIPDet

     - name: Print HOST IP
       debug:
          msg: "host IP: {{ hostIPDet.stdout }}"

     - name: add host to group azure-vm
       add_host:
          name: "{{ hostIPDet.stdout }}"
          groups: azure-vm

    - name: Make vars persistant
      
          
- name: Install Mysql
  hosts: azure-vm
  become: yes
  gather_facts: yes
  roles:
    - { role: mysql, when: stat_result.stat.exists == False }

- name: Install Tomcat 
  hosts: azure-vm
  remote_user: ansibleusr
  vars:
    app_version: "{{ version }}"
  roles:
    - tomcat8
